# Análise Passagens de Avião Rio - Berlim

## Import e função de scraping

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

from bs4 import BeautifulSoup
import re

import datetime
import time

import pandas as pd

option = webdriver.ChromeOptions()

#Argumentos para "driblar" o bloqueio de bots
option.add_argument('--disable-blink-features=AutomationControlled')
option.add_argument("window-size=1280,800")
option.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36")
option.add_argument(r"user-data-dir=C:\Users\lgrne\OneDrive\Documents\AULAS PUC BI\Projeto Final\selenium\Default")

s = Service(r'C:\Users\lgrne\Documents\chromedriver.exe')

In [2]:
def skyscanner_precos_ber(ida, volta, sleep_time=2):

    precos = []
    
    # Manipulação da url de busca. Podemos editar origem, destino e datas à vontade aqui.
    
    url = "https://www.skyscanner.com.br/transporte/passagens-aereas/rioa/ber/" + str(ida) + "/" +\
           str(volta) + "/?adults=1&adultsv2=1&cabinclass=economy&children=0&childrenv2=&destination"\
           "entityid=27547053&inboundaltsenabled=false&infants=0&originentityid=27541837&outboundaltsenabled=false"\
           "&preferdirects=false&ref=home&rtn=1"
    
    driver.get("https://www.skyscanner.com.br/")
    time.sleep(15) #Há trechos de sleep ao longo do código para ajudar a "driblar" a detecção de bots

    driver.get(url)
    time.sleep(20)
      
    soup = BeautifulSoup(driver.page_source, "html.parser")

    # O site do Skyscanner fica carregando os resultados durante um tempo variável. 
    # Esse trecho garante que só busquemos o valor mais barato quando de fato ele terminar de carregar. 
    # Enquanto a página não for carregada corretamente, um aviso "Página ainda não carregada" será exibido.
    
    while ("resultados" in str(soup.select('div[class*="ResultsSummary"]'))) == False:
        print("Página ainda não carregada")
        time.sleep(10)
        soup = BeautifulSoup(driver.page_source, "html.parser")
     
    
    for EachPart in soup.select('div[class*="mainPrice"]'):
        precos.append(EachPart.get_text())
        
    return precos[1]

## Scraping

In [3]:
# Lista onde os valores serão armazenados

lista_2022 = []

In [4]:
## Para 2022
dias = [1,3,6,9,12,15,18,21]
meses = [7,8,9,10,11,12]

In [5]:
# Loop de coleta para cada dia e mês explicitado nas variáveis "dias" e "meses"

for mes in meses:
    for dia in dias:
        t = (2022,mes,dia,0,0,0,0,0,0)
        secs = time.mktime(t)
        
        data_ida = datetime.datetime.fromtimestamp(secs)
        data_volta = data_ida + datetime.timedelta(days=7)
        
        driver = webdriver.Chrome(service=s, options=option)
        time.sleep(5)
        preco = skyscanner_precos_ber(data_ida.strftime("%Y%m%d"),data_volta.strftime("%Y%m%d"))
        time.sleep(5)
        driver.quit()
        
        consulta = {'Destino': 'Berlim', 'Ida': data_ida, 'Volta': data_volta, 'Preco': preco}
        lista_2022.append(consulta)

Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada
Página ainda não carregada

In [6]:
#Lista final

lista_2022

[{'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 7, 1, 0, 0),
  'Volta': datetime.datetime(2022, 7, 8, 0, 0),
  'Preco': 'R$ 9.923'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 7, 3, 0, 0),
  'Volta': datetime.datetime(2022, 7, 10, 0, 0),
  'Preco': 'R$ 8.888'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 7, 6, 0, 0),
  'Volta': datetime.datetime(2022, 7, 13, 0, 0),
  'Preco': 'R$ 8.275'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 7, 9, 0, 0),
  'Volta': datetime.datetime(2022, 7, 16, 0, 0),
  'Preco': 'R$ 9.867'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 7, 12, 0, 0),
  'Volta': datetime.datetime(2022, 7, 19, 0, 0),
  'Preco': 'R$ 8.714'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 7, 15, 0, 0),
  'Volta': datetime.datetime(2022, 7, 22, 0, 0),
  'Preco': 'R$ 8.682'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 7, 18, 0, 0),
  'Volta': datetime.datetime(2022, 7, 25, 0, 0),
  'Preco': 'R$ 9.003'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 7, 21, 0, 0),
  'Volta': datetime.datetime(2022, 7, 28, 0, 0),
  'Preco': 'R$ 8.039'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 8, 1, 0, 0),
  'Volta': datetime.datetime(2022, 8, 8, 0, 0),
  'Preco': 'R$ 7.344'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 8, 3, 0, 0),
  'Volta': datetime.datetime(2022, 8, 10, 0, 0),
  'Preco': 'R$ 7.134'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 8, 6, 0, 0),
  'Volta': datetime.datetime(2022, 8, 13, 0, 0),
  'Preco': 'R$ 7.627'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 8, 9, 0, 0),
  'Volta': datetime.datetime(2022, 8, 16, 0, 0),
  'Preco': 'R$ 6.798'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 8, 12, 0, 0),
  'Volta': datetime.datetime(2022, 8, 19, 0, 0),
  'Preco': 'R$ 6.489'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 8, 15, 0, 0),
  'Volta': datetime.datetime(2022, 8, 22, 0, 0),
  'Preco': 'R$ 6.028'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 8, 18, 0, 0),
  'Volta': datetime.datetime(2022, 8, 25, 0, 0),
  'Preco': 'R$ 5.743'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 8, 21, 0, 0),
  'Volta': datetime.datetime(2022, 8, 28, 0, 0),
  'Preco': 'R$ 6.279'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 9, 1, 0, 0),
  'Volta': datetime.datetime(2022, 9, 8, 0, 0),
  'Preco': 'R$ 6.147'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 9, 3, 0, 0),
  'Volta': datetime.datetime(2022, 9, 10, 0, 0),
  'Preco': 'R$ 6.150'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 9, 6, 0, 0),
  'Volta': datetime.datetime(2022, 9, 13, 0, 0),
  'Preco': 'R$ 5.408'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 9, 9, 0, 0),
  'Volta': datetime.datetime(2022, 9, 16, 0, 0),
  'Preco': 'R$ 5.408'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 9, 12, 0, 0),
  'Volta': datetime.datetime(2022, 9, 19, 0, 0),
  'Preco': 'R$ 5.120'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 9, 15, 0, 0),
  'Volta': datetime.datetime(2022, 9, 22, 0, 0),
  'Preco': 'R$ 5.230'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 9, 18, 0, 0),
  'Volta': datetime.datetime(2022, 9, 25, 0, 0),
  'Preco': 'R$ 5.694'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 9, 21, 0, 0),
  'Volta': datetime.datetime(2022, 9, 28, 0, 0),
  'Preco': 'R$ 6.033'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 10, 1, 0, 0),
  'Volta': datetime.datetime(2022, 10, 8, 0, 0),
  'Preco': 'R$ 5.034'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 10, 3, 0, 0),
  'Volta': datetime.datetime(2022, 10, 10, 0, 0),
  'Preco': 'R$ 4.783'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 10, 6, 0, 0),
  'Volta': datetime.datetime(2022, 10, 13, 0, 0),
  'Preco': 'R$ 4.716'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 10, 9, 0, 0),
  'Volta': datetime.datetime(2022, 10, 16, 0, 0),
  'Preco': 'R$ 4.572'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 10, 12, 0, 0),
  'Volta': datetime.datetime(2022, 10, 19, 0, 0),
  'Preco': 'R$ 4.141'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 10, 15, 0, 0),
  'Volta': datetime.datetime(2022, 10, 22, 0, 0),
  'Preco': 'R$ 5.408'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 10, 18, 0, 0),
  'Volta': datetime.datetime(2022, 10, 25, 0, 0),
  'Preco': 'R$ 3.797'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 10, 21, 0, 0),
  'Volta': datetime.datetime(2022, 10, 28, 0, 0),
  'Preco': 'R$ 3.998'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 11, 1, 0, 0),
  'Volta': datetime.datetime(2022, 11, 8, 0, 0),
  'Preco': 'R$ 3.682'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 11, 3, 0, 0),
  'Volta': datetime.datetime(2022, 11, 10, 0, 0),
  'Preco': 'R$ 3.682'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 11, 6, 0, 0),
  'Volta': datetime.datetime(2022, 11, 13, 0, 0),
  'Preco': 'R$ 3.878'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 11, 9, 0, 0),
  'Volta': datetime.datetime(2022, 11, 16, 0, 0),
  'Preco': 'R$ 3.916'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 11, 12, 0, 0),
  'Volta': datetime.datetime(2022, 11, 19, 0, 0),
  'Preco': 'R$ 4.643'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 11, 15, 0, 0),
  'Volta': datetime.datetime(2022, 11, 22, 0, 0),
  'Preco': 'R$ 3.823'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 11, 18, 0, 0),
  'Volta': datetime.datetime(2022, 11, 25, 0, 0),
  'Preco': 'R$ 3.612'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 11, 21, 0, 0),
  'Volta': datetime.datetime(2022, 11, 28, 0, 0),
  'Preco': 'R$ 3.414'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 12, 1, 0, 0),
  'Volta': datetime.datetime(2022, 12, 8, 0, 0),
  'Preco': 'R$ 3.682'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 12, 3, 0, 0),
  'Volta': datetime.datetime(2022, 12, 10, 0, 0),
  'Preco': 'R$ 5.120'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 12, 6, 0, 0),
  'Volta': datetime.datetime(2022, 12, 13, 0, 0),
  'Preco': 'R$ 4.840'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 12, 9, 0, 0),
  'Volta': datetime.datetime(2022, 12, 16, 0, 0),
  'Preco': 'R$ 5.870'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 12, 12, 0, 0),
  'Volta': datetime.datetime(2022, 12, 19, 0, 0),
  'Preco': 'R$ 4.889'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 12, 15, 0, 0),
  'Volta': datetime.datetime(2022, 12, 22, 0, 0),
  'Preco': 'R$ 6.273'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 12, 18, 0, 0),
  'Volta': datetime.datetime(2022, 12, 25, 0, 0),
  'Preco': 'R$ 5.286'},
 {'Destino': 'Berlim',
  'Ida': datetime.datetime(2022, 12, 21, 0, 0),
  'Volta': datetime.datetime(2022, 12, 28, 0, 0),
  'Preco': 'R$ 5.202'}]

In [7]:
# Criação do dataframe

df_2022 = pd.DataFrame(lista_2022)

In [8]:
df_2022.head()

  Destino        Ida      Volta     Preco
0  Berlim 2022-07-01 2022-07-08  R$ 9.923
1  Berlim 2022-07-03 2022-07-10  R$ 8.888
2  Berlim 2022-07-06 2022-07-13  R$ 8.275
3  Berlim 2022-07-09 2022-07-16  R$ 9.867
4  Berlim 2022-07-12 2022-07-19  R$ 8.714

In [9]:
df_2022.tail()

   Destino        Ida      Volta     Preco
43  Berlim 2022-12-09 2022-12-16  R$ 5.870
44  Berlim 2022-12-12 2022-12-19  R$ 4.889
45  Berlim 2022-12-15 2022-12-22  R$ 6.273
46  Berlim 2022-12-18 2022-12-25  R$ 5.286
47  Berlim 2022-12-21 2022-12-28  R$ 5.202

In [10]:
#Export para csv

df_2022.to_csv("berlim_2022.csv", encoding='utf-8')